#!/bin/bash
source /etc/file_clients/config.sh

host="$(hostname)"

#if [ ! -e "${torrent_dir}settings.json" ]; then
#	echo '{
#	"rpc-enabled": true,
#	"rpc-authentication-required": false,
#    "lpd-enabled": true,
#    "utp-enabled": false
#	}' > "${torrent_dir}settings.json"
#fi

ssh -q -i /root/.ssh/id_rsa ${server_ip} "
	for i in \$(ls $map_files_dir); do
		q=0
		cur_date=\$(echo \$i | cut -d \"_\" -f2)
		while read -r linea; do
			if [[ ${host} == \$linea ]]; then
				q=\$((q + 1))
			fi
		done < ${map_files_dir}\$i

		if [ \$q -eq 1 ]; then
			echo \"$host\" >> \"${map_files_dir}\$i\"
			echo \"${torrent_files_dir}*\${cur_date}*\"
		fi
done
" | xargs -I {} scp -q -i /root/.ssh/id_rsa "${server_ip}:{}" ${torrent_dir}.

for x in $(ls $torrent_dir | grep ".torrent" ); do
	ssh -q -i /root/.ssh/id_rsa ${server_ip} "
	if ! ls ${torrent_files_dir} | grep -q $x ; then
		echo ${x}_2
	elif ! ps aux | grep -v grep | grep -q ${x} ; then
		echo ${x}_1
	elif ps aux | grep -v grep | grep -q ${x} ; then
		echo ${x}_0
	fi
	"
done | xargs -I {} bash -c 'if [[ {} == *_2 ]]; then
	echo {}
	rm '${torrent_dir}'$(echo {} | cut -d "_" -f 1)
elif [[ {} == *_1 ]]; then
	echo "el fichero $(echo {} | cut -d "_" -f 1) no está activo, no se hace nada"
elif [[ {} == *_0  ]]; then
	echo {}
	transmission-cli -w '${downloads_dir}' -g '${torrent_dir}' '${torrent_dir}'$(echo {} | cut -d "_" -f 1) #> /dev/null 2>&1 &	
fi'
